on:
    issues:
        types: [opened]
jobs:
    test_job:
        runs-on: ubuntu-latest
        name: A to test action
        steps:
            - name: test
              uses: valonsogit/lete-action-ts@v1.2
              with:
                  sex: ${{ secrets.VALONSOGIT }}
              
