on:
  issues:
    types: [opened]
jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A to test action
    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
      - name: test
        uses: valonsogit/lete-action-ts@v1
        with:
          secrets: ${{ toJSON(secrets) }}
          secretKey: TOKEN_${{ github.actor }}
          outputName: SEX_MACHINE
      - name: "Print ouput of previous step"
        run: echo "$SEX_MACHINE"
      - name: "Print full env"
        run: printenv
